---
Gemfile:
  optional:
    ':test':
      - gem: 'hiera'
spec/spec_helper_acceptance.rb:
  managed: true
.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_documentation
    - parameter_types
spec/spec_helper.rb:
  facterdb_string_keys: true
